// src/pages/Home.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Map from '../components/Map.svelte';
  import PinCard from '../components/PinCard.svelte';
  import RegisterModal from '../components/RegisterModal.svelte';
  import { getPublicPins, type Pin } from '../lib/supabase';
  import { eventDate, formatDate } from '../lib/format';

  let pins = $state<Pin[]>([]);
  let loading = $state(true);
  let loadError = $state('');
  let view = $state<'map' | 'list'>('map');
  let selectedId = $state<string | null>(null);
  let focus = $state<{ lat: number; lng: number; n: number } | null>(null);
  let registerOpen = $state(false);
  let selectedDate = $state(eventDate());

  let dates = $derived([...new Set(pins.map((p) => p.date))].sort());
  let visible = $derived(pins.filter((p) => p.date === selectedDate));

  onMount(async () => {
    try {
      pins = await getPublicPins();
      if (dates.length > 0 && !dates.includes(selectedDate)) {
        selectedDate = dates[0];
      }
    } catch {
      loadError = 'Não foi possível carregar os pins. Tenta recarregar a página.';
    } finally {
      loading = false;
    }
  });

  function focusPin(pin: Pin): void {
    view = 'map';
    selectedId = pin.id;
    focus = { lat: pin.lat, lng: pin.lng, n: Date.now() };
  }
</script>

<div class="page home">
  <header>
    <div class="brand">
      <span class="logo">🎃</span>
      <div>
        <h1>Doces ou Travessuras</h1>
        <p class="tagline">Casas com doces para o Halloween em Portugal</p>
      </div>
    </div>
    <div class="actions">
      {#if dates.length > 0}
        <select class="date-select" bind:value={selectedDate} aria-label="Dia">
          {#each dates as d}
            <option value={d}>{formatDate(d)}</option>
          {/each}
        </select>
      {/if}
      <div class="toggle" role="tablist">
        <button role="tab" class:active={view === 'map'} onclick={() => (view = 'map')}>Mapa</button>
        <button role="tab" class:active={view === 'list'} onclick={() => (view = 'list')}>Lista</button>
      </div>
      <button class="cta" onclick={() => (registerOpen = true)}>Registar a minha casa</button>
    </div>
  </header>

  <main class:list-mode={view === 'list'}>
    {#if loading}
      <p class="status">A carregar pins… 🎃</p>
    {:else if loadError}
      <p class="status error">{loadError}</p>
    {:else if view === 'map'}
      <Map pins={visible} {focus} onSelect={(pin) => (selectedId = pin.id)} />
    {:else}
      <div class="list">
        {#if visible.length === 0}
          <p class="status">
            Ainda não há casas com doces neste dia. Sê o primeiro a adicionar a tua! 🍬
          </p>
        {:else}
          {#each visible as pin (pin.id)}
            <PinCard {pin} selected={pin.id === selectedId} onclick={() => focusPin(pin)} />
          {/each}
        {/if}
      </div>
    {/if}
  </main>

  <footer>
    <span>
      Dados geográficos ©
      <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap contributors</a>
    </span>
    <span>Feito com 🎃 em Portugal</span>
  </footer>

  {#if registerOpen}
    <RegisterModal onClose={() => (registerOpen = false)} />
  {/if}
</div>

// src/pages/Home.tsx
import { useEffect, useMemo, useState } from 'react';
import Map from '../components/Map';
import PinCard from '../components/PinCard';
import RegisterModal from '../components/RegisterModal';
import { getPublicPins, type Pin } from '../lib/supabase';
import { eventDate, formatDate } from '../lib/format';

export default function Home() {
  const [pins, setPins] = useState<Pin[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState('');
  const [view, setView] = useState<'map' | 'list'>('map');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [focus, setFocus] = useState<{ lat: number; lng: number; n: number } | null>(null);
  const [registerOpen, setRegisterOpen] = useState(false);
  const [selectedDate, setSelectedDate] = useState(eventDate());

  const dates = useMemo(() => [...new Set(pins.map((pin) => pin.date))].sort(), [pins]);
  const visiblePins = useMemo(
    () => pins.filter((pin) => pin.date === selectedDate),
    [pins, selectedDate],
  );

  useEffect(() => {
    let active = true;

    void getPublicPins()
      .then((nextPins) => {
        if (!active) return;
        setPins(nextPins);
        const nextDates = [...new Set(nextPins.map((pin) => pin.date))].sort();
        if (nextDates.length > 0 && !nextDates.includes(eventDate())) {
          setSelectedDate(nextDates[0]);
        }
      })
      .catch(() => {
        if (active) setLoadError('Não foi possível carregar os pins. Tenta recarregar a página.');
      })
      .finally(() => {
        if (active) setLoading(false);
      });

    return () => {
      active = false;
    };
  }, []);

  function focusPin(pin: Pin): void {
    setView('map');
    setSelectedId(pin.id);
    setFocus({ lat: pin.lat, lng: pin.lng, n: Date.now() });
  }

  return (
    <div className="page home">
      <header>
        <div className="brand">
          <span className="logo">🎃</span>
          <div>
            <h1>Doces ou Travessuras</h1>
            <p className="tagline">Casas com doces para o Halloween em Portugal</p>
          </div>
        </div>
        <div className="actions">
          {dates.length > 0 && (
            <select
              className="date-select"
              value={selectedDate}
              onChange={(event) => setSelectedDate(event.target.value)}
              aria-label="Dia"
            >
              {dates.map((date) => (
                <option value={date} key={date}>
                  {formatDate(date)}
                </option>
              ))}
            </select>
          )}
          <div className="toggle" role="tablist">
            <button
              role="tab"
              className={view === 'map' ? 'active' : undefined}
              aria-selected={view === 'map'}
              onClick={() => setView('map')}
            >
              Mapa
            </button>
            <button
              role="tab"
              className={view === 'list' ? 'active' : undefined}
              aria-selected={view === 'list'}
              onClick={() => setView('list')}
            >
              Lista
            </button>
          </div>
          <button className="cta" type="button" onClick={() => setRegisterOpen(true)}>
            Registar a minha casa
          </button>
        </div>
      </header>

      <main className={view === 'list' ? 'list-mode' : undefined}>
        {loading ? (
          <p className="status">A carregar pins… 🎃</p>
        ) : loadError ? (
          <p className="status error">{loadError}</p>
        ) : view === 'map' ? (
          <Map pins={visiblePins} focus={focus} onSelect={(pin) => setSelectedId(pin.id)} />
        ) : (
          <div className="list">
            {visiblePins.length === 0 ? (
              <p className="status">
                Ainda não há casas com doces neste dia. Sê o primeiro a adicionar a tua! 🍬
              </p>
            ) : (
              visiblePins.map((pin) => (
                <PinCard
                  pin={pin}
                  selected={pin.id === selectedId}
                  onClick={() => focusPin(pin)}
                  key={pin.id}
                />
              ))
            )}
          </div>
        )}
      </main>

      <footer>
        <span>
          Dados geográficos ©{' '}
          <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">
            OpenStreetMap contributors
          </a>
        </span>
        <span>Feito com 🎃 em Portugal</span>
      </footer>

      {registerOpen && <RegisterModal onClose={() => setRegisterOpen(false)} />}
    </div>
  );
}
